name: sorcerers_server
description: A server app using the shelf package and Docker.
version: 1.0.0
repository: https://github.com/filippo-orru/sorcerers-server
publish_to: none

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.0
  uuid: ^4.4.2
  sorcerers_core:
    path: ./packages/core

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
